spring:
  profiles:
    include:
      - datasource
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  main:
    allow-bean-definition-overriding: true
server:
  port: 8090